- name: Odroid-GitOps bootstrap & maintenance
  hosts: localhost
  connection: local
  become: true
  gather_facts: true

  vars:

    bootstrap_timer_git_repo: "https://github.com/Mankianer/HomeCastle-ansible.git"
    bootstrap_timer_user: "root" # TODO: User anpassen
    bootstrap_timer_ssh_key: false # TODO: SSH-Key erstellen


    microk8s_version: "1.32/stable"
    microk8s_plugins:
      ingress: true
      helm3: true

    #    microk8s_primary_user: "manki"
    #    microk8s_channel: "1.32/stable"
    #    microk8s_addons_extra:
    #      - registry

    #    fluxcd_bootstrap_provider: "github"
    #    fluxcd_repo_owner: "Mankianer"
    #    fluxcd_repo_name: "HomeCastle"
    #    fluxcd_repo_branch: "main"
    #    fluxcd_repo_path: "clusters/castle-kingdom"

    # ── Auth ──────────────────────────────────────────────────────
    flux_ssh_identity: "/root/.ssh/id_ed25519"

  # ─── optionale Vorbedingungen ──────────────────────────
  pre_tasks:
    - name: Ensure base packages required by roles are present
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - rsync
      tags: prerequisites

  # ─── Rollen in definierter Reihenfolge ─────────────────
  roles:
    - role: host_hardening
      tags: hardening

    - role: bootstrap_timer
      tags: bootstrap

    - role: microk8s
      tags: k8s

    - role: linuxbrew
      tags: linuxbrew

    - role: fluxcd
      tags: flux
