---
- name: Reload SSH
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart Fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reload UFW
  community.general.ufw:
    state: reloaded
