---
- name: "Add fluxcd tap : {{ fluxcd_linuxbrew_user_name }}"
  become_user: "{{ fluxcd_linuxbrew_user_name }}"
  become: false
  community.general.homebrew_tap:
    name: fluxcd/tap
    state: present

- name: Install Flux CLI
  become_user: "{{ fluxcd_linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: fluxcd/tap/flux
    state: present
    update_homebrew: true

- name: Verify installation
  become_user: "{{ fluxcd_linuxbrew_user_name }}"
  become: false
  ansible.builtin.command: "flux --version"
  register: fluxcd_version
  changed_when: false

- name: Show installed Flux version
  ansible.builtin.debug:
    msg: "{{ fluxcd_version.stdout }}"
