---
- name: Ensure Flux CLI is present via Homebrew
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: fluxcd/tap/flux
    state: present

- name: Add fluxcd tap
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew_tap:
    name: fluxcd/tap
    path: "{{ fluxcd_linuxbrew_prefix_user }}"
    state: present

- name: Install Flux CLI
  become_user: "{{ linuxbrew_user_name }}"
  become: true
  community.general.homebrew:
    name: flux
    state: present
    path: "{{ fluxcd_linuxbrew_prefix_user }}"
    update_homebrew: true

- name: Verify installation
  ansible.builtin.command: "{{ fluxcd_linuxbrew_prefix_user }} flux --version"
  register: fluxcd_version
  changed_when: false

- name: Show installed Flux version
  ansible.builtin.debug:
    msg: "{{ fluxcd_version.stdout }}"
