---
# Snap channel (siehe `sudo snap info microk8s`)
microk8s_channel: "1.32/stable"

# Add-ons, die nach der Installation aktiviert werden sollen
microk8s_addons_default:
  - dns
  - hostpath-storage
  - ingress
  - metrics-server      # optional, aber n체tzlich

# Zus채tzliche Add-ons (kannst du aus site.yml 체berschreiben/erweitern)
microk8s_addons_extra: []

# Benutzer, der zur Gruppe microk8s hinzugef체gt wird
microk8s_primary_user: "{{ ansible_user | default('ubuntu') }}"

# Sektionen, die du bei Bedarf einschalten kannst
microk8s_copy_kubeconfig: true
microk8s_kubeconfig_path: "/home/{{ microk8s_primary_user }}/.kube"
