---
- name: Ensure required packages are present
  ansible.builtin.apt:
    name:
      - ufw
      - fail2ban
      - unattended-upgrades
    state: present
    update_cache: true
  tags: packages

# ── SSH Hardening ────────────────────────────────────────
- name: Disable password auth for SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    create: false
  notify: Reload SSH
  tags: ssh

- name: Set custom SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ host_hardening_ssh_port }}"
    create: false
  notify: Reload SSH
  when: host_hardening_ssh_port != 22
  tags: ssh

# ── Firewall (UFW) ───────────────────────────────────────
- name: Reset UFW (clean slate)
  community.general.ufw:
    state: reset
    direction: incoming
  tags: ufw

- name: Set default UFW policies
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
  tags: ufw

- name: Allow configured TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ host_hardening_open_tcp_ports }}"   # TODO: add ssh port here
  tags: ufw

- name: Allow configured UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
  loop: "{{ host_hardening_open_udp_ports }}"
  tags: ufw

- name: Enable UFW logging
  community.general.ufw:
    logging: 'on'
  tags: ufw

# ── Fail2Ban ─────────────────────────────────────────────
- name: Deploy Fail2Ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: "0644"
  notify: Restart Fail2ban
  tags: fail2ban

# ── Unattended-Upgrades ──────────────────────────────────
- name: Deploy unattended-upgrades config
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
  tags: updates

- name: Enable unattended-upgrades timer
  ansible.builtin.systemd:
    name: unattended-upgrades.service
    enabled: true
    state: started
  tags: updates
